version: 2
stages:
  build:
    machine: true
    working_directory: /home/circleci/go/src/github.com/drud/ghlabel

    environment:
      GOPATH: /home/circleci/go

    steps:
      - run: mkdir -p ~/go/src/github.com/drud/ghlabel && mkdir -p ~/go/lib && mkdir -p ~/go/bin

      - checkout

      - run: make linux
      - run: make staticcheck
      - run: make test
      - store_artifacts:
                path: bin
                name: Artifact storage